### ISSUE TITLE
Incorrect Data and Genre Doesn't Appear

### ISSUE THREAD

**Issue by tls123yeong** [febryardiansyah/manga-api#10]
Hi,
I am one of your Manga API github users. very good project and help me.

But here I want to tell you that there is a problem with the API you suggested in the latest issue https://mangamint.azurewebsites.net/api/ in genres and Detail Manga there is a problem not displaying the desired data. also the API url https://mangamint.azurewebsites.net/api/manga/page/1 only displays manga types, whereas previously featured comics of all types. And the Recommended and Popular API urls display the same thumbnails.

I hope you reply to this issues and fix the issues,Thank you. 
Full Respectfully

1. https://mangamint.azurewebsites.net/api/manga/page/1
2. https://mangamint.azurewebsites.net/api/genres/
3. https://mangamint.azurewebsites.net/api/recommended
4. https://mangamint.azurewebsites.net/api/manga/popular/page/1
5. https://mangamint.azurewebsites.net/api/manga/detail/after-transformation-mine-and-her-wild-fantasy/
6. https://mangamint.azurewebsites.net/api/cari/komi%20san

**Comment by febryardiansyah** [comment]
Hi, thanks for opening an issue.
Wow, there are many issues after i Update the API xD. 
A'ight, this would be takes a lot of time. But, i would fix as fast as posible
Thanks

**Comment by febryardiansyah** [comment]
TO DO :
- [ ] Genres not displaying the desired data
- [ ] Detail Manga not displaying the desired data
- [ ] https://mangamint.azurewebsites.net/api/manga/page/1 only displays manga types
- [ ] Recommended and Popular API urls display the same thumbnails

**Comment by tls123yeong** [comment]
Thank you, for responding to this problem

I'll be waiting for this API fix :)

**Comment by febryardiansyah** [comment]
Hi, for the genres issue. i was checking this url https://mangamint.kaedenoki.net/api/genres and it shows as expected. I dont know why it is not shown on this url https://mangamint.azurewebsites.net/api/genres/. Maybe it because the website using cloudflare and azure can't access the website.
