### ISSUE TITLE
Detail manga & Read chapter

### ISSUE THREAD

**Issue by zakirkun** [febryardiansyah/manga-api#14]
Detail manga sering null result dan di read chapter imagenya ga valid

**Comment by febryardiansyah** [comment]
btw, lu pake yg mangamint.kadenoki.net ya ? klo iya, di image chapter nya result nya gini kan ```https://i0.wp.com/img.komiku.co.id/norundefined``` itu padahal udh tak fix kemarin, di cpanel git repository nya udh update tp yg nodejs app nya gk update njit :" . Klo pake azure dia langsung update padahal https://mangamint.azurewebsites.net/api/chapter/after-transformation-mine-and-her-wild-fantasy-chapter-70-bahasa-indonesia/.

klo yg detail, gw sejauh ini belum dapet result null sih.

Btw thanks udh open issue, gw coba lapor cs di cpanel nya dulu.

**Comment by zakirkun** [comment]
Iya bang gw soalnya pakai di rn sering null result kalau get detail manga sama gambar dari chapter juga norundefined

**Comment by febryardiansyah** [comment]
buat skrng pake yg ini dulu https://mangamint.azurewebsites.net/api/ , cuma yg genres gk bisa ke get. ke block kayaknya, klo mau nampilin genre list nya bisa pake yg ini https://mangamint.kaedenoki.net/api/

**Comment by zakirkun** [comment]
Okay bang

**Comment by sunbonggg** [comment]
API detail -  kadang nilai null, harus refres berapa kali baru keluar data
https://mangamint.kaedenoki.net/api/manga/detail/boruto-id/
API chapter - gambar undefined semua
https://mangamint.kaedenoki.net/api/chapter/after-transformation-mine-and-her-wild-fantasy-chapter-70-bahasa-indonesia/
*https://mangamint.azurewebsites.net/api/ pakai ini untuk chapter ada gambar yg undefined juga
mohon pencerahanny, terimakasi mas
