### ISSUE TITLE
API detil n chapter gambar error

### ISSUE THREAD

**Issue by sunbonggg** [febryardiansyah/manga-api#15]
API detail - kadang nilai null, harus refres berapa kali baru keluar data
https://mangamint.kaedenoki.net/api/manga/detail/boruto-id/
API chapter - gambar undefined semua
https://mangamint.kaedenoki.net/api/chapter/after-transformation-mine-and-her-wild-fantasy-chapter-70-bahasa-indonesia/
*https://mangamint.azurewebsites.net/api/ pakai ini untuk chapter ada gambar yg undefined juga
mohon pencerahanny, terimakasi mas

**Comment by febryardiansyah** [comment]
Ini issue sebenernya sama kayak ini #14 

untuk yg detail gw juga belum tau masalahnya dmn, bisa jadi di website originalnya https://komiku.id/.
klo yg gambar, pake yg azurewebsites itu yg undifined yg mana ya ? bisa kasih url/ss nya

**Comment by sunbonggg** [comment]
semua API mangamint.kaedenoki.net sekarang error 404 not found.
untuk azurewebsites yg undifined itu contoh komik one piece chapter baru, klo chapter lama ada gambarnya.
mohon bantuan, API jadi error semua. terimakasi

**Comment by febryardiansyah** [comment]
tadi sebenernya mau ku update di hosting nya, cuma gk tau kenapa malah error semua.
harus lapor cs dulu ini mah, untk sementara pake yg azurewebsites dulu ya

**Comment by febryardiansyah** [comment]
untuk yg https://mangamint.kaedenoki.net/api/ udh bisa di akses kembali, cuma gk tau kenapa di hosting nya gk mau update ngikutin repositori ini. buat skrng pake yg azurewebsites dulu klo mau akses yg chapter https://mangamint.azurewebsites.net/api/chapter/after-transformation-mine-and-her-wild-fantasy-chapter-70-bahasa-indonesia/

Thanks
