### ISSUE TITLE
Manga detail tokyo卍revengers Request path contains unescaped characters 

### ISSUE THREAD

**Issue by NicolaDonoastro** [febryardiansyah/manga-api#20]
- [x] message : " Request path contains unescaped characters"
- [x] url : https://mangamint.kaedenoki.net/api/manga/detail/tokyo%E5%8D%8Drevengers/

**Comment by febryardiansyah** [comment]
Thanks for opening this issue, i've checked it and it said as you said. I'll fix this as fast as possible

Thank you

**Comment by febryardiansyah** [comment]
Fixed 🔥
![image](https://user-images.githubusercontent.com/33514300/104305444-453dbe00-54ff-11eb-9a8f-7503021a8aa7.png)
