### ISSUE TITLE
"Request failed with status code 403"

### ISSUE THREAD

**Issue by msyahrul801** [febryardiansyah/manga-api#21]
saya coba deploy pake ubuntu server 18.04 lts server USA apakah itu pengaruh dari server atau gimana ?

http://54.147.44.129:3000/api/manga/page/1

dan untuk scrap itu otomatis ya ?

**Comment by febryardiansyah** [comment]
klo di lihat dari status code nya sih sepertinya iya, servernya gk bisa akses website yang di scraping. kemungkinan website yg discraping menggunakan cors. saranku, coba pake server asia

scraping otomatis dijalankan ketika url dibuka
Thanks
