### ISSUE TITLE
empty result when getting manga details

### ISSUE THREAD

**Issue by ilhamefo** [febryardiansyah/manga-api#27]
jadi ketika GET manga detail sering return empty.

![Screenshot_14](https://user-images.githubusercontent.com/12053306/121848444-378d9e00-cd14-11eb-9f6b-fde6eac259e6.jpg)

tapi terkadang memang bisa tampil return response yg diinginkan

![Screenshot_15](https://user-images.githubusercontent.com/12053306/121848548-64da4c00-cd14-11eb-935e-c74811cc11af.jpg)

saya gak tau ini bug atau fitur, jika ini bug tolong diperbaiki. jika ini fitur kok begini?

**Comment by Nunu27** [comment]
emang dari webnya itu, kalo kurang "/" kadang keredirect ke homepage. kalo mau get manga detail coba id kasih "/" manual, encode uri tapi jadinya `${manga_id}%2F`
