### ISSUE TITLE
Invalid parameter - =PRODUCTION

### ISSUE THREAD

**Issue by Reresize** [febryardiansyah/manga-api#7]
When i run 'npm run start' i get this error;
`> MODE=PRODUCTION node index.js
Invalid parameter - =PRODUCTION`

**Comment by febryardiansyah** [comment]
@Reresize hi !! thanks for opening issue, Sorry for late response. in that case, i suggest u to remove "MODE=PRODUCTION" in scripts packages.json.

**Comment by Reresize** [comment]
Thanks :) it's worked
