### ISSUE TITLE
manga_list kosong pada enpoint manga, manhwa, dan manhua

### ISSUE THREAD

**Issue by zavierferodova** [febryardiansyah/manga-api#8]
Halo, ini manga scraper yang bagus 👍👍👍
Namun saat saya mengambil data dengan 3 endpoint berikut data manga_list menjadi kosong.

Kurasa masalah tersebut disebabkan karena saat AxiosService mengambil data ke [https://komiku.co.id/manga/page/1](https://komiku.co.id/manga/page/1) itu dialihkan ke sumber [https://komiku.id/pustaka/](https://komiku.id/pustaka/)

1. [https://mangamint.kaedenoki.net/api/manga/page/1](https://mangamint.kaedenoki.net/api/manga/page/1)
2. [https://mangamint.kaedenoki.net/api/manhua/1](https://mangamint.kaedenoki.net/api/manhua/1)
3. [https://mangamint.kaedenoki.net/api/manhua/1](https://mangamint.kaedenoki.net/api/manhua/1)

Response :
`{
    "status": true,
    "message": "success",
    "manga_list": []
}`

**Comment by febryardiansyah** [comment]
@zavierferodova Hi, Terimakasih sudah melaporkan issue ini 🙌. Untuk daftar manga (https://mangamint.kaedenoki.net/api/manga/page/1) sudah bisa digunakan, untuk manhua dan manhwa akan segera saya perbaiki.
Thanks 😊

**Comment by zakirkun** [comment]
Webnya pakai cloudflare jadi mungkin salah satu penyebabnya banyak blank

**Comment by zavierferodova** [comment]
Iya kak, yang pakai cloudflare itu dibagian detail manga

**Comment by zakirkun** [comment]
[Api Dari Saya](https://dev-komik.pojokan.my.id/

**Comment by febryardiansyah** [comment]
@zakirkun Bener banget, web nya pake cloudflare (aku tau dari fp webnya di fb). tp kayanya bukan itu masalahnya, soalnya response nya masin 200. pas aku cek tampilannya udh beda dari sblumnya, kemungkinan stuktur htmlnya udh berubah.

@zavierferodova mungkin buat skrng bisa pake Api yg di berikan sama mas @zakirkun https://dev-komik.pojokan.my.id/

**Comment by zavierferodova** [comment]
Terimakasih sarannya @febryardiansyah  @zakirkun

**Comment by muhammadzakirramadhan** [comment]
Nah pikirku juga gitu, bisa jadi ada kode html yang di ubah

**Comment by febryardiansyah** [comment]
Api nya udh bisa digunakan kembali, pake nya yg ini dulu https://mangamint.azurewebsites.net/api/
Soalnya cpanelnya gaje banget sumpah gk mau update.
Aku close aja ya issue ini, klo ada issue lg yang sama bisa open lg aja atau buat issue baru
Thanks
